services:
  postgres:
    image: postgres:17.5-bookworm
    restart: always
    environment:
      POSTGRES_DB: backtest-pro
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgresData:/var/lib/postgresql/data
    ports:
      - "5434:5432"
volumes:
  postgresData: