CREATE TYPE "public"."tradeGrade" AS ENUM('A', 'B', 'C', 'D', 'E', 'F');--> statement-breakpoint
CREATE TYPE "public"."tradeStatus" AS ENUM('win', 'loss', 'tie');--> statement-breakpoint
CREATE TYPE "public"."tradeTag" AS ENUM('long', 'short', 'both');--> statement-breakpoint
CREATE TABLE "symbolsPairs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "symbolsPairs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(20) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkUserID" varchar(255) NOT NULL,
	"symbol" varchar(20) NOT NULL,
	"tag" "tradeTag",
	"entryTime" varchar(30),
	"exitTime" varchar(30),
	"entryDate" date,
	"exitDate" date,
	"entryPrice" integer,
	"exitPrice" integer,
	"tradeStatus" "tradeStatus",
	"riskToReward" integer,
	"actualRiskToReward" integer,
	"riskToTrade" integer,
	"profitNLoss" integer,
	"tradeGrade" "tradeGrade",
	"newsDay" boolean DEFAULT false,
	"impactOfNewsDay" integer,
	"mistakeDescription" text,
	"strategyDescription" text,
	"learningDescription" text
);
