CREATE TYPE "public"."tradeGrade" AS ENUM('A', 'B', 'C', 'D', 'E', 'F');--> statement-breakpoint
CREATE TYPE "public"."tradeStatus" AS ENUM('win', 'loss', 'tie');--> statement-breakpoint
CREATE TYPE "public"."tradeTag" AS ENUM('long', 'short', 'both');--> statement-breakpoint
CREATE TABLE "trade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"symbol" varchar(20) NOT NULL,
	"tag" "tradeTag",
	"entry_time" varchar(30),
	"exit_time" varchar(30),
	"entry_price" integer,
	"exit_price" integer,
	"trade_status" "tradeStatus",
	"risk_to_reward" integer,
	"actual_risk_to_reward" integer,
	"risk_to_trade" integer,
	"profit_loss" integer,
	"trade_grade" "tradeGrade",
	"news_day" boolean DEFAULT false,
	"impact_of_news_day" integer,
	"mistake" text,
	"strategy_description" text,
	"learning_description" text
);
