export const coins = [
    { value: "BTC", label: "BTC" },
    { value: "ETH", label: "ETH" },
    {
        value: "XRP",
        label: "XRP",
    },
    { value: "LTC", label: "LTC" },
    { value: "BNB", label: "BNB" },
    { value: "ADA", label: "ADA" },
    {
        value: "DOT",
        label: "DOT",
    },
    { value: "DOGE", label: "DOGE" },
    { value: "SOL", label: "SOL" },
    { value: "AVAX", label: "AVAX" },
    {
        value: "MATIC",
        label: "MATIC",
    },
    { value: "SHIB", label: "SHIB" },
    { value: "LINK", label: "LINK" },
    { value: "UNI", label: "UNI" },
    {
        value: "SUSHI",
        label: "SUSHI",
    },
    { value: "AAVE", label: "AAVE" },
    { value: "COMP", label: "COMP" },
    { value: "YFI", label: "YFI" },
    {
        value: "USDC",
        label: "USDC",
    },
    { value: "USDT", label: "USDT" },
    { value: "BUSD", label: "BUSD" },
    { value: "LUNA", label: "LUNA" },
    {
        value: "SXP",
        label: "SXP",
    },
    { value: "MATIC", label: "MATIC" },
    { value: "FTM", label: "FTM" },
    { value: "TRX", label: "TRX" },
    {
        value: "XMR",
        label: "XMR",
    },
    { value: "XTZ", label: "XTZ" },
    { value: "XEM", label: "XEM" },
    { value: "XRP", label: "XRP" },
    {
        value: "XLM",
        label: "XLM",
    },
    { value: "XVG", label: "XVG" },
    { value: "ZEC", label: "ZEC" },
    { value: "XEM", label: "XEM" },
    {
        value: "XRP",
        label: "XRP",
    },
    { value: "XLM", label: "XLM" },
    { value: "XVG", label: "XVG" },
    { value: "ZEC", label: "ZEC" },
];
