export const TradeTags = ["long", "short", "both"];
export const TradeStatus = ["win", "loss", "none"];
export const TradeGrade = ["A", "B", "C", "D", "E"];

export function getTradeData() {
    return [
        {
            symbol: "AAPL",
            tag: "long",
            entryTime: "09:30",
            exitTime: "15:45",
            entryDate: new Date("2025-07-01"),
            exitDate: new Date("2025-07-01"),
            entryPrice: 190.5,
            exitPrice: 195.75,
            tradeStatus: "win",
            riskToReward: 2.5,
            actualRiskToReward: 2.3,
            riskToTrade: 100,
            profitNLoss: 230,
            tradeGrade: "A",
            newsDay: false,
            impactOfNewsDay: "None",
            mistakeDescription: "No mistake",
            strategyDescription: "Breakout",
            learningDescription: "Volume confirmation helped.",
        },
        {
            symbol: "GOOG",
            tag: "short",
            entryTime: "10:00",
            exitTime: "14:30",
            entryDate: new Date("2025-07-02"),
            exitDate: new Date("2025-07-02"),
            entryPrice: 2800,
            exitPrice: 2760,
            tradeStatus: "win",
            riskToReward: 3.0,
            actualRiskToReward: 3.1,
            riskToTrade: 150,
            profitNLoss: 465,
            tradeGrade: "S",
            newsDay: true,
            impactOfNewsDay: "High volatility",
            mistakeDescription: "None",
            strategyDescription: "Reversal",
            learningDescription: "Waited for confirmation.",
        },
        {
            symbol: "MSFT",
            tag: "long",
            entryTime: "11:15",
            exitTime: "13:45",
            entryDate: new Date("2025-07-03"),
            exitDate: new Date("2025-07-03"),
            entryPrice: 345,
            exitPrice: 350,
            tradeStatus: "win",
            riskToReward: 2.0,
            actualRiskToReward: 2.2,
            riskToTrade: 100,
            profitNLoss: 200,
            tradeGrade: "A",
            newsDay: false,
            impactOfNewsDay: "N/A",
            mistakeDescription: "None",
            strategyDescription: "Trend continuation",
            learningDescription: "Trust the trend.",
        },
        {
            symbol: "TSLA",
            tag: "short",
            entryTime: "10:30",
            exitTime: "14:00",
            entryDate: new Date("2025-07-04"),
            exitDate: new Date("2025-07-04"),
            entryPrice: 750,
            exitPrice: 735,
            tradeStatus: "win",
            riskToReward: 1.5,
            actualRiskToReward: 1.6,
            riskToTrade: 120,
            profitNLoss: 180,
            tradeGrade: "B",
            newsDay: false,
            impactOfNewsDay: "N/A",
            mistakeDescription: "Late entry",
            strategyDescription: "Breakdown retest",
            learningDescription: "Be earlier next time.",
        },
        {
            symbol: "AMZN",
            tag: "long",
            entryTime: "09:45",
            exitTime: "15:00",
            entryDate: new Date("2025-07-05"),
            exitDate: new Date("2025-07-05"),
            entryPrice: 130,
            exitPrice: 128,
            tradeStatus: "loss",
            riskToReward: 2.0,
            actualRiskToReward: -1.0,
            riskToTrade: 100,
            profitNLoss: -100,
            tradeGrade: "D",
            newsDay: true,
            impactOfNewsDay: "Sudden reversal",
            mistakeDescription: "Didn’t check macro news",
            strategyDescription: "Breakout",
            learningDescription: "Always check economic calendar.",
        },
        {
            symbol: "NFLX",
            tag: "long",
            entryTime: "11:00",
            exitTime: "13:30",
            entryDate: new Date("2025-07-06"),
            exitDate: new Date("2025-07-06"),
            entryPrice: 400,
            exitPrice: 410,
            tradeStatus: "win",
            riskToReward: 2.5,
            actualRiskToReward: 2.8,
            riskToTrade: 90,
            profitNLoss: 250,
            tradeGrade: "S",
            newsDay: false,
            impactOfNewsDay: "None",
            mistakeDescription: "None",
            strategyDescription: "Pullback entry",
            learningDescription: "Great patience.",
        },
        {
            symbol: "META",
            tag: "short",
            entryTime: "10:15",
            exitTime: "14:30",
            entryDate: new Date("2025-07-07"),
            exitDate: new Date("2025-07-07"),
            entryPrice: 320,
            exitPrice: 310,
            tradeStatus: "win",
            riskToReward: 2.2,
            actualRiskToReward: 2.0,
            riskToTrade: 110,
            profitNLoss: 220,
            tradeGrade: "A",
            newsDay: true,
            impactOfNewsDay: "Earnings report helped",
            mistakeDescription: "None",
            strategyDescription: "News fade",
            learningDescription: "Earnings can work in your favor.",
        },
        {
            symbol: "NVDA",
            tag: "long",
            entryTime: "09:30",
            exitTime: "12:30",
            entryDate: new Date("2025-07-08"),
            exitDate: new Date("2025-07-08"),
            entryPrice: 450,
            exitPrice: 455,
            tradeStatus: "tie",
            riskToReward: 2.0,
            actualRiskToReward: 0,
            riskToTrade: 100,
            profitNLoss: 0,
            tradeGrade: "C",
            newsDay: false,
            impactOfNewsDay: "None",
            mistakeDescription: "Tight stop",
            strategyDescription: "Range breakout",
            learningDescription: "Allow more room to move.",
        },
        ...Array.from({ length: 99 }).map((_, i) => ({
            symbol: `SYM${i + 1}`,
            tag: i % 2 === 0 ? "long" : "short",
            entryTime: "09:30",
            exitTime: "15:30",
            entryDate: new Date(`2025-07-${9 + i}`),
            exitDate: new Date(`2025-07-${9 + i}`),
            entryPrice: 100 + i * 5,
            exitPrice: 100 + i * 5 + (i % 3 === 0 ? -2 : 5),
            tradeStatus: i % 3 === 0 ? "loss" : "win",
            riskToReward: 2.0,
            actualRiskToReward: i % 3 === 0 ? -1.0 : 2.5,
            riskToTrade: 100,
            profitNLoss: i % 3 === 0 ? -100 : 250,
            tradeGrade: i % 3 === 0 ? "D" : i % 2 === 0 ? "A" : "B",
            newsDay: i % 4 === 0,
            impactOfNewsDay: i % 4 === 0 ? "Volatile day" : "None",
            mistakeDescription: i % 3 === 0 ? "Bad entry" : "None",
            strategyDescription: i % 2 === 0 ? "Breakout" : "Reversal",
            learningDescription: "Keep improving.",
        })),
    ];
}
